{
  "topo_file": "topos/topo_1_gs_motif_side_m.txt",
  "node_to_sat_or_gs_mapping_file": "mapping/mapping_motif_paris_kuiper_630_side_m.txt",  
  "cni_dir": "bash-cni-plugin",
  "constellation_name": "Kuiper-630",
  "num_masters": 1,
  "num_workers": 4,
  "num_gs": 1,
  "num_dummy": 2,
  "num_isls": 4,
  "main_gs": "Paris",
  "main_gs_id": "g0",
  "destination_gs": "",
  "destination_gs_id": "",
  "main_node": "1",
  "node_network": "172.16.0.0/16",
  "pod_network": "10.244.0.0/16",
  "pod_subnet": "10.244.0.0/24",
  "timestep_granularity": "60", 
  "simulation_time": "36000",
  "cpus": 4,
  "memory": 6000,
  "gs_cpus": 1,
  "gs_memory": 4000,
  "dummy_cpus": 1,
  "dummy_memory": 4000,
  "isl_bandwidth": 20,
  "gs_bandwidth": 5,
}