{
  "topo_file": "topo.txt",
  "node_to_sat_or_gs_mapping_file": "node_to_sat_or_gs_mapping.txt",  
  "cni_dir": "bash-cni-plugin",
  "constellation_name": "Starlink-550",
  "num_masters": 1,
  "num_workers": 4,
  "num_gs": 2,
  "num_isls": 4,
  "main_gs": "Paris",
  "main_gs_id": "g0",
  "destination_gs": "Moskva-(Moscow)",
  "destination_gs_id": "g1",
  "main_node": "m0",
  "node_network": "172.16.0.0/16",
  "pod_network": "10.244.0.0/16",
  "pod_subnet": "10.244.0.0/24",
  "timestep_granularity": "60", 
  "simulation_time": "36000",
  "cpus": 4,
  "memory": 6000,
  "gs_cpus": 1,
  "gs_memory": 4000,
  "isl_bandwidth": 20,
  "gs_bandwidth": 5,
}