{
  "topo_file": "topos/cset/topo_2_gs_plus_grid_side_m_v2.txt",
  "node_to_sat_or_gs_mapping_file": "mapping/cset/mapping_plus_grid_sao_paulo_fortaleza_starlink_550_side_m.txt",  
  "cni_dir": "bash-cni-plugin",
  "constellation_name": "Starlink-550",
  "init_isl_topo": "isls_plus_grid",
  "num_masters": 1,
  "num_workers": 5,
  "num_gs": 2,
  "num_dummy": 0,
  "num_isls": 4,
  "main_gs": "Paris",
  "main_gs_id": "g0",
  "destination_gs": "Madrid",
  "destination_gs_id": "g1",
  "main_node": "0",
  "node_network": "172.16.0.0/16",
  "pod_network": "10.244.0.0/16",
  "pod_subnet": "10.244.0.0/24",
  "timestep_granularity": "60", 
  "simulation_time": "36000",
  "cpus": 2,
  "memory": 4000,
  "gs_cpus": 1,
  "gs_memory": 4000,
  "dummy_cpus": 1,
  "dummy_memory": 4000,
  "isl_bandwidth": 20,
  "gs_bandwidth": 5,
}